#!/usr/bin/env ruby

require 'optparse'

options = {
    :path => '~/.git-credentials'
}
OptionParser.new do |opts|
    opts.banner = 'USAGE: git-credential-read-only [options] <action>'
    opts.on('--file', 'Specify path') do |path|
        options[:path] = path
    end
end.parse!

p options
p ARGV
